# Generated by Django 5.1.7 on 2025-04-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recomendacao',
            unique_together={('livro', 'pessoa')},
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='destinatario',
        ),
    ]
